global:
  scrape_interval: 60s 
rule_files:
  - '/etc/prometheus/alerts/*.yml'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - prometheus-alertmanager:9093 


scrape_configs: 
  - 
    job_name: prometheus
    scrape_interval: 120s
    static_configs: 
      - 
        targets: 
          - "localhost:9090"
  - 
    job_name: blackbox
    metrics_path: /probe
    relabel_configs: 
      - 
        source_labels: 
          - __address__
        target_label: __param_target
      - 
        source_labels: 
          - __param_target
        target_label: instance
      - 
        replacement: "blackbox:9115"
        target_label: __address__
    scrape_interval: 120s
    static_configs: 
      - 
        targets: 
          - "https://www.madraswasteexchange.com"
          - "https://staging.madraswasteexchange.com"
 
    
